# Generated by Django 4.1.6 on 2023-03-17 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0002_usercreation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercreation',
            old_name='temp_password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='usercreation',
            name='password2',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
