# Generated by Django 4.1.6 on 2023-03-28 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuestAccounting', '0007_alter_userprofile_profile_pic_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=30, unique=True)),
                ('account_number', models.CharField(max_length=10, unique=True)),
                ('account_description', models.CharField(max_length=150)),
                ('normal_side', models.DecimalField(decimal_places=2, max_digits=6)),
                ('account_category', models.CharField(max_length=20)),
                ('account_subcategory', models.CharField(max_length=20)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.CharField(max_length=2)),
                ('statement', models.CharField(max_length=2)),
                ('comment', models.TextField(blank=True)),
                ('activated', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
