# Generated by Django 4.1.6 on 2023-03-29 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QuestAccounting', '0009_alter_accountmodel_normal_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
