# Generated by Django 4.1.6 on 2023-04-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0012_generalledger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralLedger',
        ),
    ]
