# Generated by Django 4.1.6 on 2023-04-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0014_generalledger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralLedger',
            new_name='JournalEntries',
        ),
    ]
