# Generated by Django 4.1.6 on 2023-04-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0015_rename_generalledger_journalentries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentries',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
