# Generated by Django 4.1.6 on 2023-04-10 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0018_eventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='account_changed',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='after_image',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='before_image',
            field=models.CharField(max_length=30),
        ),
    ]
