# Generated by Django 4.1.6 on 2023-04-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0021_delete_usercreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='journalentriesmodel',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='approved', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RejectedJournalEntriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=10)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestAccounting.accountmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PendingJournalEntriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=10)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestAccounting.accountmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AllJournalEntriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=10)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestAccounting.accountmodel')),
            ],
        ),
    ]
