# Generated by Django 4.1.6 on 2023-04-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0021_delete_usercreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentriesmodel',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
