# Generated by Django 4.1.6 on 2023-04-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0022_eventlog_status_journalentriesmodel_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlog',
            name='status',
        ),
        migrations.AlterField(
            model_name='pendingjournalentriesmodel',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='rejectedjournalentriesmodel',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='rejected', max_length=10),
        ),
    ]
