# Generated by Django 4.1.6 on 2023-04-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0024_alter_alljournalentriesmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alljournalentriesmodel',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rejectedjournalentriesmodel',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
