# Generated by Django 4.1.6 on 2023-04-27 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0026_alter_accountmodel_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(blank=True, null=True, upload_to='journal_entry_documents')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestAccounting.journalentriesmodel')),
            ],
        ),
    ]
