# Generated by Django 4.1.6 on 2023-04-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0027_journalentrydocuments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentrydocuments',
            old_name='document',
            new_name='image_document',
        ),
        migrations.AddField(
            model_name='journalentrydocuments',
            name='file_document',
            field=models.FileField(blank=True, null=True, upload_to='journal_entry_documents'),
        ),
    ]
