# Generated by Django 4.1.6 on 2023-05-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0028_rename_document_journalentrydocuments_image_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatiosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_type', models.CharField(max_length=30)),
                ('ratio_value', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
