# Generated by Django 4.1.6 on 2023-03-24 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0004_remove_usercreation_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrequest',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='accountrequest',
            name='created_at',
        ),
    ]
