# Generated by Django 4.1.6 on 2023-03-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0008_accountmodel_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='normal_side',
            field=models.CharField(max_length=6),
        ),
    ]
