# Generated by Django 4.1.6 on 2023-04-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0013_delete_generalledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestAccounting.accountmodel')),
            ],
        ),
    ]
