# Generated by Django 4.1.6 on 2023-04-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0016_alter_journalentries_credit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JournalEntries',
            new_name='JournalEntriesModel',
        ),
    ]
