# Generated by Django 4.1.6 on 2023-04-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestAccounting', '0019_eventlog_account_changed_alter_eventlog_after_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlog',
            name='event_type',
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='after_image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='before_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
